# Generated by Django 5.0.6 on 2024-06-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='User',
            new_name='user',
        ),
    ]
